### ISSUE TITLE
Image loaded event and Animator

### ISSUE THREAD

**Issue by thang2410199** [thomaslevesque/XamlAnimatedGif#11]
Hello, thanks for the fantastic lib. However, I have problem with getting the Animator dependency property.

I set the AnimationBehavior.SourceUri property via SetValue, and right after that attempt to get the animator, but the returned value is null.

Another thing: I want to get a call back when the gif is loaded and ready to play, so I can display a loading indicator for the image.

Thank you.

**Comment by thomaslevesque** [comment]
Hi,

The two problems are related. It's because the image is loaded asynchronously, so right after you set `SourceUri`, the `Animator` isn't ready yet. I plan on adding two things:

- a `Loaded` event that is raised when the `Animator` has been created
- async versions of `SetSourceUri`and `SetSourceStream` that return a `Task` that can be awaited by the calling code

**Comment by thomaslevesque** [comment]
Just added the `Loaded` event; it is raised when the animation has been fully loaded.
Note: in the WPF version, it's implemented as an attached event, whereas in the WinRT version it's a normal CLR event, because WinRT doesn't support custom routed events.

I eventually didn't add the async versions of `SetSourceUri` and `SetSourceStream`: it's not possible, because loading of the animation has to be done in the property change callbacks of the attached properties.
